<?php
if (!isset($_SESSION['user_id'])) {
  header("Location: dashboard.php?page=forbidden");
  exit;
}

$toast_message = '';
$toast_type = '';
$current_user_id = $_SESSION['user_id'];

// Handle Actions (Add / Delete Generated Report Log)
if ($_SERVER["REQUEST_METHOD"] === "POST" && isset($_POST['action'])) {
  if ($_POST['action'] === 'add') {
    $report_type = trim($_POST['report_type']);
    $file_path   = trim($_POST['file_path']);

    if (!empty($report_type) && !empty($file_path)) {
      try {
        $stmt = $pdo->prepare("INSERT INTO generated_reports (generated_by, report_type, file_path, generated_at) VALUES (?, ?, ?, NOW())");
        $stmt->execute([$current_user_id, $report_type, $file_path]);

        $toast_message = "Generated report record created successfully!";
        $toast_type = "Success";
      } catch (PDOException $e) {
        $toast_message = "Error recording report: " . $e->getMessage();
        $toast_type = "Error";
      }
    } else {
      $toast_message = "Please fill in all required fields.";
      $toast_type = "Error";
    }
  } elseif ($_POST['action'] === 'delete') {
    $report_file_id = intval($_POST['report_file_id']);

    try {
      // Fetch file path first if you wish to unlink physical files
      $fetch_stmt = $pdo->prepare("SELECT file_path FROM generated_reports WHERE report_file_id = ?");
      $fetch_stmt->execute([$report_file_id]);
      $report = $fetch_stmt->fetch(PDO::FETCH_ASSOC);

      if ($report && file_exists($report['file_path'])) {
        @unlink($report['file_path']);
      }

      $stmt = $pdo->prepare("DELETE FROM generated_reports WHERE report_file_id = ?");
      $stmt->execute([$report_file_id]);
      
      $toast_message = "Report record deleted successfully!";
      $toast_type = "Success";
    } catch (PDOException $e) {
      $toast_message = "Error deleting report: " . $e->getMessage();
      $toast_type = "Error";
    }
  }
}

// Fetch generated reports with details of the user who generated them
try {
  $stmt = $pdo->query("
    SELECT 
      gr.report_file_id,
      gr.report_type,
      gr.file_path,
      gr.generated_at,
      CONCAT(u.First_name, ' ', u.Last_name) AS generated_by_name,
      r.role_name
    FROM generated_reports gr
    INNER JOIN users u ON gr.generated_by = u.user_id
    LEFT JOIN roles r ON u.role_id = r.role_id
    ORDER BY gr.generated_at DESC
  ");
  $reports = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
  die("Database Error: " . $e->getMessage());
}
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Generated Reports</h1>
        </div>
        <div class="col-sm-6 text-right">
          <button type="button" class="btn bg-navy btn-sm" data-toggle="modal" data-target="#addReportModal">
            <i class="fas fa-file-export mr-1"></i> Log New Report File
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">

      <?php if (!empty($toast_message)): ?>
        <div class="alert alert-<?= $toast_type === 'Success' ? 'success' : 'danger' ?> alert-dismissible fade show" role="alert">
          <?= htmlspecialchars($toast_message) ?>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <?php endif; ?>

      <div class="row">
        <div class="col-lg-12">
          <div class="card card-navy card-outline">
            <div class="card-header">
              <h3 class="card-title"><i class="fas fa-folder-open mr-1"></i> Exported System Reports</h3>
            </div>
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Report Type</th>
                    <th>Generated By</th>
                    <th>File Path</th>
                    <th>Generated At</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($reports as $index => $rp): ?>
                    <tr>
                      <td><?= $index + 1 ?></td>
                      <td><strong><?= htmlspecialchars($rp['report_type']) ?></strong></td>
                      <td>
                        <?= htmlspecialchars($rp['generated_by_name']) ?>
                        <span class="badge badge-info ml-1"><?= ucfirst(htmlspecialchars($rp['role_name'] ?? 'User')) ?></span>
                      </td>
                      <td><code><?= htmlspecialchars($rp['file_path']) ?></code></td>
                      <td><?= date('M d, Y h:i A', strtotime($rp['generated_at'])) ?></td>
                      <td>
                        <!-- Download / View File Link -->
                        <a href="<?= htmlspecialchars($rp['file_path']) ?>" target="_blank" class="btn btn-info btn-sm" title="Download / Open File">
                          <i class="fas fa-download"></i>
                        </a>

                        <!-- Delete Form -->
                        <form action="" method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to delete this report file record?');">
                          <input type="hidden" name="action" value="delete">
                          <input type="hidden" name="report_file_id" value="<?= $rp['report_file_id'] ?>">
                          <button type="submit" class="btn btn-danger btn-sm" title="Delete Record">
                            <i class="fas fa-trash"></i>
                          </button>
                        </form>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Add Generated Report Log Modal -->
<div class="modal fade" id="addReportModal" tabindex="-1" role="dialog" aria-labelledby="addReportModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-navy text-white">
        <h5 class="modal-title" id="addReportModalLabel"><i class="fas fa-file-export mr-1"></i> Log Generated Report</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="POST">
        <div class="modal-body">
          <input type="hidden" name="action" value="add">

          <div class="form-group">
            <label for="report_type">Report Type <span class="text-danger">*</span></label>
            <select name="report_type" id="report_type" class="form-control form-control-sm" required>
              <option value="">-- Select Report Type --</option>
              <option value="Attendance Summary">Attendance Summary</option>
              <option value="Session Performance">Session Performance</option>
              <option value="Tutor Evaluation Report">Tutor Evaluation Report</option>
              <option value="Student Progress Overview">Student Progress Overview</option>
              <option value="System Audit Log">System Audit Log</option>
            </select>
          </div>

          <div class="form-group">
            <label for="file_path">File Path / URL <span class="text-danger">*</span></label>
            <input type="text" name="file_path" id="file_path" class="form-control form-control-sm" placeholder="e.g., uploads/reports/attendance_2026_09.pdf" required>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
          <button type="submit" class="btn bg-navy btn-sm">Save Record</button>
        </div>
      </form>
    </div>
  </div>
</div>